name: Build OSX binaries

on:
  - push
  - pull_request

jobs:
  osx:
    runs-on: macos-12
    steps:
      - run: brew install zmq sdl2 libelf
      - run: pip3 install meson
      - run: pip3 install ninja
      - uses: actions/checkout@v3
      - run: meson setup ./build
      - run: ninja -C ./build
      - run: meson install -C ./build --destdir ./install
      - uses: actions/upload-artifact@v4
        with:
          name: orbuculum-osx
          path: build/install/**/*
          if-no-files-found: error


